#!/bin/bash

echo "start training the model"
CUDA_VISIBLE_DEVICES=2 python main.py

echo "-------------------------------training model end------------------------------"
echo "-------------------------------start testing the model-------------------------"

python test.py
echo "------------------------------testing model end---------------------------------"
echo "-----------------count image metrics and event metrics-------------------------"
#need pred files
python count_metric.py

echo "-------------------generate gallery_CME.json and query_CME.json----------------"
CUDA_VISIBLE_DEVICES=2 python generate_gallery.py
python image_to_incident.py
python generate_similar_event.py

echo "----------------------show example pictures-------------------------------------"
#need similar_event.csv(generated by generate_similar_event)
python find_k_similar_images.py CME20110914000005
